# Generated by Django 5.1.5 on 2025-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='commune',
            field=models.CharField(default='Abidjan', max_length=100, verbose_name='Commune'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='quartier',
            field=models.CharField(default='Rue12', max_length=100, verbose_name='Quartier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='zone',
            field=models.CharField(default='Zone A', max_length=100, verbose_name='Zone'),
            preserve_default=False,
        ),
    ]
