# Generated by Django 5.1.5 on 2025-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_latitude_supplier_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='date_creation',
            field=models.CharField(default='01012025', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='registre',
            field=models.CharField(default='CI6MMPO', max_length=100),
            preserve_default=False,
        ),
    ]
