# Generated by Django 5.1.5 on 2025-05-06 06:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_frequency', models.IntegerField(help_text='Fréquence de réapprovisionnement en jours (0-365)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.category')),
                ('frequence_appr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.frequenceapprovisionnement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopscollecte', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Produit collecté',
                'verbose_name_plural': 'Produits collectés',
                'indexes': [models.Index(fields=['owner'], name='shopscollec_owner_i_e7dcbd_idx'), models.Index(fields=['supplier'], name='shopscollec_supplie_107d6b_idx'), models.Index(fields=['created_at'], name='shopscollec_created_33ebf4_idx'), models.Index(fields=['category'], name='shopscollec_categor_b6312d_idx')],
            },
        ),
    ]
