# Generated by Django 5.1.5 on 2025-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
