# Generated by Django 5.1.5 on 2025-04-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_modulepermission4_delete_modulepermission3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='modulepermission4',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.module4'),
        ),
        migrations.DeleteModel(
            name='Module3',
        ),
    ]
