# Generated by Django 5.1.5 on 2025-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_contact_email_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_creation',
            field=models.CharField(default='01012025', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='registre',
            field=models.CharField(default='CI-M-2025', max_length=100),
            preserve_default=False,
        ),
    ]
