# Generated by Django 5.1.5 on 2025-05-06 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_gender', models.CharField(max_length=10)),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequence_appr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.frequenceapprovisionnement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to=settings.AUTH_USER_MODEL)),
                ('taille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.tailleshop')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.shoptype')),
                ('typecommerce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.typecommerce')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'indexes': [models.Index(fields=['owner'], name='shops_shop_owner_i_de9788_idx'), models.Index(fields=['created_at'], name='shops_shop_created_8bca73_idx'), models.Index(fields=['type'], name='shops_shop_type_id_0af686_idx'), models.Index(fields=['typecommerce'], name='shops_shop_typecom_83c170_idx'), models.Index(fields=['taille'], name='shops_shop_taille__a4507a_idx')],
            },
        ),
    ]
