# Generated by Django 5.1.5 on 2025-02-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='shops/')),
                ('type', models.CharField(choices=[('BRANDED', 'Brandée'), ('NON_BRANDED', 'Non brandée')], max_length=20)),
                ('typecommerce', models.CharField(choices=[('BRANDED', 'Brandée'), ('NON_BRANDED', 'Non brandée')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_gender', models.CharField(max_length=10)),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
