# Generated by Django 5.1.5 on 2025-02-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='typecommerce',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
