# Generated by Django 5.1.5 on 2025-02-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_typecommerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='taille',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
