# Generated by Django 5.1.5 on 2025-03-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_frequence_appr'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='categorie',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
