# Generated by Django 5.1.5 on 2025-02-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourcollecte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercollecte',
            name='email',
            field=models.EmailField(default='issa@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliercollecte',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliercollecte',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliercollecte',
            name='phone',
            field=models.CharField(default=778882517.0, max_length=15),
            preserve_default=False,
        ),
    ]
